version: '3.8'

services:
  app:
    build: .
    container_name: lixozen-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=lixo
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin123
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_FLYWAY_ENABLED=true
    networks:
      - lixozen-network
    restart: unless-stopped

networks:
  lixozen-network:
    driver: bridge