CREATE TABLE coletas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tipo_residuo VARCHAR2(100),
    quantidade_kg NUMBER,
    data_coleta DATE,
    localizacao VARCHAR2(255),
    responsavel VARCHAR2(100)
);
